require 'bundler'
require "rubygems/package"

FUBUDOCS_FOLDER = File.dirname(__FILE__)
COMPILE_TARGET = @solution.options[:compilemode]
ARTIFACTS = File.expand_path('../artifacts', FUBUDOCS_FOLDER)

module Bundler
  class GemHelper
    class << self
      def install_tasks(opts = {})
        opts[:name] = 'fubudocs'
        opts[:dir] = File.dirname(__FILE__)
        new(opts[:dir], opts[:name]).install
      end
    end

    def build_gem
      @gemspec = Bundler.load_gemspec(@spec_path)


      Dir.chdir(FUBUDOCS_FOLDER) do
        @gemspec.files = Dir.glob("bin/**/*").to_a
        puts @gemspec.files
        Gem::Package::build @gemspec, true
      end
    end
  end
end

namespace :gem do
  require "bundler/gem_tasks"

  %w{install release}.each do |task|
    Rake::Task["gem:#{task}"].clear
  end

  task :archive => %w{compile prepare_bin build} do
    Dir.chdir(FUBUDOCS_FOLDER) do
      copyOutputFiles '.', '*.gem', ARTIFACTS
    end
  end

  desc "Installs a local copy of the gem"
  task :install => :archive do 
    Dir.chdir ARTIFACTS do
      gem_file = Dir.glob("*.gem").sort.last
      sh "gem install #{gem_file}"
    end
  end

  desc "copies the files necessary to build the gemspec to the bin directory"
  task :prepare_bin => :clean do
    dir = "src/FubuDocsRunner/bin/#{COMPILE_TARGET}/"

    FileUtils.mkdir_p File.expand_path("bin/fubudocs_exe", FUBUDOCS_FOLDER)
    FileUtils.cp_r "#{dir}/.", File.expand_path('bin/fubudocs_exe/.', FUBUDOCS_FOLDER)
  end

  desc "cleans up gem artifacts"
  task :clean do
    Dir.chdir(FUBUDOCS_FOLDER) do
      ['bin/fubudocs_exe'].each do |d|
        FileUtils.rm_rf d
        FileUtils.mkdir_p d
      end

      Dir.glob("*.gem").each  do |f|
        FileUtils.rm f
      end

    end
  end
end
